name: Build and Test React App

on:
  push:
    branches: [ "master" ] # Ensure your default branch name is correct (e.g., "main" or "master").
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # List Node.js versions for compatibility testing.

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enables caching for faster builds.

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the app (if the script exists)
    - name: Build the React app
      run: npm run build --if-present

    # Step 5: Run tests
    - name: Run tests
      if: false
      run: npm test
